import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { documentType, details } = await req.json();

    if (!documentType || typeof documentType !== "string" || documentType.length > 100) {
      return new Response(JSON.stringify({ error: "Invalid document type" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (!details || typeof details !== "string" || details.length > 5000) {
      return new Response(JSON.stringify({ error: "Invalid details" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const systemPrompt = `You are Doc Builder at AI KOACHED. Generate a COMPLETE, professional, ready-to-use legal document.

OUTPUT FORMAT: Return ONLY the document text — no JSON wrapping, no markdown code blocks. Just the raw document content with proper formatting using line breaks and sections.

DOCUMENT REQUIREMENTS:
- Include ALL standard legal clauses for the document type
- Use placeholder brackets like [COMPANY NAME], [DATE], [STATE], [PARTY A NAME] etc.
- Include signature blocks at the end
- Be thorough — this should be a real, usable document
- Include proper section numbering
- Add a disclaimer at the very end: "DISCLAIMER: This document was generated by AI KOACHED for educational and template purposes. We recommend having a licensed attorney review before execution."

SUPPORTED DOCUMENTS: Operating Agreement, NDA (Mutual/One-Way), Service Agreement, Employment Agreement, Independent Contractor Agreement, Partnership Agreement, Terms of Service, Privacy Policy (GDPR/CCPA/LGPD), Bylaws, Articles of Incorporation, Cease & Desist, Non-Compete Agreement, Buy-Sell Agreement, Consulting Agreement, Franchise Agreement, Lease Agreement, Shareholder Agreement

INTERNATIONAL: Adapt to the jurisdiction mentioned — UK, Nigeria, UAE, India, Canada, Australia, EU, etc.

NEVER use "promise" or "guarantee."`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Generate a complete ${documentType} document with these details:\n\n${details}` },
        ],
      }),
    });

    if (!response.ok) {
      return new Response(JSON.stringify({ error: "Document generation service unavailable" }), {
        status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || "";

    return new Response(JSON.stringify({ document: content }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("doc gen error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
