/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpireRouteImport } from './routes/empire'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpireRevenueRouteImport } from './routes/empire.revenue'
import { Route as EmpirePricingRouteImport } from './routes/empire.pricing'
import { Route as EmpireOnboardingRouteImport } from './routes/empire.onboarding'
import { Route as EmpireMarketsRouteImport } from './routes/empire.markets'
import { Route as EmpireLegalRouteImport } from './routes/empire.legal'
import { Route as EmpireKoachRouteImport } from './routes/empire.koach'
import { Route as EmpireGrantsRouteImport } from './routes/empire.grants'
import { Route as EmpireEntityRouteImport } from './routes/empire.entity'
import { Route as EmpireCreditRouteImport } from './routes/empire.credit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpireRoute = EmpireRouteImport.update({
  id: '/empire',
  path: '/empire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpireRevenueRoute = EmpireRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpirePricingRoute = EmpirePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireOnboardingRoute = EmpireOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireMarketsRoute = EmpireMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireLegalRoute = EmpireLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireKoachRoute = EmpireKoachRouteImport.update({
  id: '/koach',
  path: '/koach',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireGrantsRoute = EmpireGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireEntityRoute = EmpireEntityRouteImport.update({
  id: '/entity',
  path: '/entity',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireCreditRoute = EmpireCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => EmpireRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empire': typeof EmpireRouteWithChildren
  '/login': typeof LoginRoute
  '/empire/credit': typeof EmpireCreditRoute
  '/empire/entity': typeof EmpireEntityRoute
  '/empire/grants': typeof EmpireGrantsRoute
  '/empire/koach': typeof EmpireKoachRoute
  '/empire/legal': typeof EmpireLegalRoute
  '/empire/markets': typeof EmpireMarketsRoute
  '/empire/onboarding': typeof EmpireOnboardingRoute
  '/empire/pricing': typeof EmpirePricingRoute
  '/empire/revenue': typeof EmpireRevenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empire': typeof EmpireRouteWithChildren
  '/login': typeof LoginRoute
  '/empire/credit': typeof EmpireCreditRoute
  '/empire/entity': typeof EmpireEntityRoute
  '/empire/grants': typeof EmpireGrantsRoute
  '/empire/koach': typeof EmpireKoachRoute
  '/empire/legal': typeof EmpireLegalRoute
  '/empire/markets': typeof EmpireMarketsRoute
  '/empire/onboarding': typeof EmpireOnboardingRoute
  '/empire/pricing': typeof EmpirePricingRoute
  '/empire/revenue': typeof EmpireRevenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empire': typeof EmpireRouteWithChildren
  '/login': typeof LoginRoute
  '/empire/credit': typeof EmpireCreditRoute
  '/empire/entity': typeof EmpireEntityRoute
  '/empire/grants': typeof EmpireGrantsRoute
  '/empire/koach': typeof EmpireKoachRoute
  '/empire/legal': typeof EmpireLegalRoute
  '/empire/markets': typeof EmpireMarketsRoute
  '/empire/onboarding': typeof EmpireOnboardingRoute
  '/empire/pricing': typeof EmpirePricingRoute
  '/empire/revenue': typeof EmpireRevenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empire'
    | '/login'
    | '/empire/credit'
    | '/empire/entity'
    | '/empire/grants'
    | '/empire/koach'
    | '/empire/legal'
    | '/empire/markets'
    | '/empire/onboarding'
    | '/empire/pricing'
    | '/empire/revenue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empire'
    | '/login'
    | '/empire/credit'
    | '/empire/entity'
    | '/empire/grants'
    | '/empire/koach'
    | '/empire/legal'
    | '/empire/markets'
    | '/empire/onboarding'
    | '/empire/pricing'
    | '/empire/revenue'
  id:
    | '__root__'
    | '/'
    | '/empire'
    | '/login'
    | '/empire/credit'
    | '/empire/entity'
    | '/empire/grants'
    | '/empire/koach'
    | '/empire/legal'
    | '/empire/markets'
    | '/empire/onboarding'
    | '/empire/pricing'
    | '/empire/revenue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpireRoute: typeof EmpireRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire': {
      id: '/empire'
      path: '/empire'
      fullPath: '/empire'
      preLoaderRoute: typeof EmpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire/revenue': {
      id: '/empire/revenue'
      path: '/revenue'
      fullPath: '/empire/revenue'
      preLoaderRoute: typeof EmpireRevenueRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/pricing': {
      id: '/empire/pricing'
      path: '/pricing'
      fullPath: '/empire/pricing'
      preLoaderRoute: typeof EmpirePricingRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/onboarding': {
      id: '/empire/onboarding'
      path: '/onboarding'
      fullPath: '/empire/onboarding'
      preLoaderRoute: typeof EmpireOnboardingRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/markets': {
      id: '/empire/markets'
      path: '/markets'
      fullPath: '/empire/markets'
      preLoaderRoute: typeof EmpireMarketsRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/legal': {
      id: '/empire/legal'
      path: '/legal'
      fullPath: '/empire/legal'
      preLoaderRoute: typeof EmpireLegalRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/koach': {
      id: '/empire/koach'
      path: '/koach'
      fullPath: '/empire/koach'
      preLoaderRoute: typeof EmpireKoachRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/grants': {
      id: '/empire/grants'
      path: '/grants'
      fullPath: '/empire/grants'
      preLoaderRoute: typeof EmpireGrantsRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/entity': {
      id: '/empire/entity'
      path: '/entity'
      fullPath: '/empire/entity'
      preLoaderRoute: typeof EmpireEntityRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/credit': {
      id: '/empire/credit'
      path: '/credit'
      fullPath: '/empire/credit'
      preLoaderRoute: typeof EmpireCreditRouteImport
      parentRoute: typeof EmpireRoute
    }
  }
}

interface EmpireRouteChildren {
  EmpireCreditRoute: typeof EmpireCreditRoute
  EmpireEntityRoute: typeof EmpireEntityRoute
  EmpireGrantsRoute: typeof EmpireGrantsRoute
  EmpireKoachRoute: typeof EmpireKoachRoute
  EmpireLegalRoute: typeof EmpireLegalRoute
  EmpireMarketsRoute: typeof EmpireMarketsRoute
  EmpireOnboardingRoute: typeof EmpireOnboardingRoute
  EmpirePricingRoute: typeof EmpirePricingRoute
  EmpireRevenueRoute: typeof EmpireRevenueRoute
}

const EmpireRouteChildren: EmpireRouteChildren = {
  EmpireCreditRoute: EmpireCreditRoute,
  EmpireEntityRoute: EmpireEntityRoute,
  EmpireGrantsRoute: EmpireGrantsRoute,
  EmpireKoachRoute: EmpireKoachRoute,
  EmpireLegalRoute: EmpireLegalRoute,
  EmpireMarketsRoute: EmpireMarketsRoute,
  EmpireOnboardingRoute: EmpireOnboardingRoute,
  EmpirePricingRoute: EmpirePricingRoute,
  EmpireRevenueRoute: EmpireRevenueRoute,
}

const EmpireRouteWithChildren =
  EmpireRoute._addFileChildren(EmpireRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpireRoute: EmpireRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
