/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpireRouteImport } from './routes/empire'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpireRevenueRouteImport } from './routes/empire.revenue'
import { Route as EmpirePricingRouteImport } from './routes/empire.pricing'
import { Route as EmpireOnboardingRouteImport } from './routes/empire.onboarding'
import { Route as EmpireMarketsRouteImport } from './routes/empire.markets'
import { Route as EmpireLegalRouteImport } from './routes/empire.legal'
import { Route as EmpireKoachRouteImport } from './routes/empire.koach'
import { Route as EmpireGrantsRouteImport } from './routes/empire.grants'
import { Route as EmpireEntityRouteImport } from './routes/empire.entity'
import { Route as EmpireCreditRouteImport } from './routes/empire.credit'
import { Route as EmpireConnectionsRouteImport } from './routes/empire.connections'
import { Route as EmpireComplianceRouteImport } from './routes/empire.compliance'
import { Route as EmpireCommunityRouteImport } from './routes/empire.community'
import { Route as EmpireBuildRouteImport } from './routes/empire.build'
import { Route as EmpireAvatarRouteImport } from './routes/empire.avatar'
import { Route as EmpireAiWorkersRouteImport } from './routes/empire.ai-workers'
import { Route as EmpireCommunityBusinessIdRouteImport } from './routes/empire.community.$businessId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpireRoute = EmpireRouteImport.update({
  id: '/empire',
  path: '/empire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpireRevenueRoute = EmpireRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpirePricingRoute = EmpirePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireOnboardingRoute = EmpireOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireMarketsRoute = EmpireMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireLegalRoute = EmpireLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireKoachRoute = EmpireKoachRouteImport.update({
  id: '/koach',
  path: '/koach',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireGrantsRoute = EmpireGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireEntityRoute = EmpireEntityRouteImport.update({
  id: '/entity',
  path: '/entity',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireCreditRoute = EmpireCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireConnectionsRoute = EmpireConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireComplianceRoute = EmpireComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireCommunityRoute = EmpireCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireBuildRoute = EmpireBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireAvatarRoute = EmpireAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireAiWorkersRoute = EmpireAiWorkersRouteImport.update({
  id: '/ai-workers',
  path: '/ai-workers',
  getParentRoute: () => EmpireRoute,
} as any)
const EmpireCommunityBusinessIdRoute =
  EmpireCommunityBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => EmpireCommunityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empire': typeof EmpireRouteWithChildren
  '/login': typeof LoginRoute
  '/empire/ai-workers': typeof EmpireAiWorkersRoute
  '/empire/avatar': typeof EmpireAvatarRoute
  '/empire/build': typeof EmpireBuildRoute
  '/empire/community': typeof EmpireCommunityRouteWithChildren
  '/empire/compliance': typeof EmpireComplianceRoute
  '/empire/connections': typeof EmpireConnectionsRoute
  '/empire/credit': typeof EmpireCreditRoute
  '/empire/entity': typeof EmpireEntityRoute
  '/empire/grants': typeof EmpireGrantsRoute
  '/empire/koach': typeof EmpireKoachRoute
  '/empire/legal': typeof EmpireLegalRoute
  '/empire/markets': typeof EmpireMarketsRoute
  '/empire/onboarding': typeof EmpireOnboardingRoute
  '/empire/pricing': typeof EmpirePricingRoute
  '/empire/revenue': typeof EmpireRevenueRoute
  '/empire/community/$businessId': typeof EmpireCommunityBusinessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empire': typeof EmpireRouteWithChildren
  '/login': typeof LoginRoute
  '/empire/ai-workers': typeof EmpireAiWorkersRoute
  '/empire/avatar': typeof EmpireAvatarRoute
  '/empire/build': typeof EmpireBuildRoute
  '/empire/community': typeof EmpireCommunityRouteWithChildren
  '/empire/compliance': typeof EmpireComplianceRoute
  '/empire/connections': typeof EmpireConnectionsRoute
  '/empire/credit': typeof EmpireCreditRoute
  '/empire/entity': typeof EmpireEntityRoute
  '/empire/grants': typeof EmpireGrantsRoute
  '/empire/koach': typeof EmpireKoachRoute
  '/empire/legal': typeof EmpireLegalRoute
  '/empire/markets': typeof EmpireMarketsRoute
  '/empire/onboarding': typeof EmpireOnboardingRoute
  '/empire/pricing': typeof EmpirePricingRoute
  '/empire/revenue': typeof EmpireRevenueRoute
  '/empire/community/$businessId': typeof EmpireCommunityBusinessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empire': typeof EmpireRouteWithChildren
  '/login': typeof LoginRoute
  '/empire/ai-workers': typeof EmpireAiWorkersRoute
  '/empire/avatar': typeof EmpireAvatarRoute
  '/empire/build': typeof EmpireBuildRoute
  '/empire/community': typeof EmpireCommunityRouteWithChildren
  '/empire/compliance': typeof EmpireComplianceRoute
  '/empire/connections': typeof EmpireConnectionsRoute
  '/empire/credit': typeof EmpireCreditRoute
  '/empire/entity': typeof EmpireEntityRoute
  '/empire/grants': typeof EmpireGrantsRoute
  '/empire/koach': typeof EmpireKoachRoute
  '/empire/legal': typeof EmpireLegalRoute
  '/empire/markets': typeof EmpireMarketsRoute
  '/empire/onboarding': typeof EmpireOnboardingRoute
  '/empire/pricing': typeof EmpirePricingRoute
  '/empire/revenue': typeof EmpireRevenueRoute
  '/empire/community/$businessId': typeof EmpireCommunityBusinessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empire'
    | '/login'
    | '/empire/ai-workers'
    | '/empire/avatar'
    | '/empire/build'
    | '/empire/community'
    | '/empire/compliance'
    | '/empire/connections'
    | '/empire/credit'
    | '/empire/entity'
    | '/empire/grants'
    | '/empire/koach'
    | '/empire/legal'
    | '/empire/markets'
    | '/empire/onboarding'
    | '/empire/pricing'
    | '/empire/revenue'
    | '/empire/community/$businessId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empire'
    | '/login'
    | '/empire/ai-workers'
    | '/empire/avatar'
    | '/empire/build'
    | '/empire/community'
    | '/empire/compliance'
    | '/empire/connections'
    | '/empire/credit'
    | '/empire/entity'
    | '/empire/grants'
    | '/empire/koach'
    | '/empire/legal'
    | '/empire/markets'
    | '/empire/onboarding'
    | '/empire/pricing'
    | '/empire/revenue'
    | '/empire/community/$businessId'
  id:
    | '__root__'
    | '/'
    | '/empire'
    | '/login'
    | '/empire/ai-workers'
    | '/empire/avatar'
    | '/empire/build'
    | '/empire/community'
    | '/empire/compliance'
    | '/empire/connections'
    | '/empire/credit'
    | '/empire/entity'
    | '/empire/grants'
    | '/empire/koach'
    | '/empire/legal'
    | '/empire/markets'
    | '/empire/onboarding'
    | '/empire/pricing'
    | '/empire/revenue'
    | '/empire/community/$businessId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpireRoute: typeof EmpireRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire': {
      id: '/empire'
      path: '/empire'
      fullPath: '/empire'
      preLoaderRoute: typeof EmpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire/revenue': {
      id: '/empire/revenue'
      path: '/revenue'
      fullPath: '/empire/revenue'
      preLoaderRoute: typeof EmpireRevenueRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/pricing': {
      id: '/empire/pricing'
      path: '/pricing'
      fullPath: '/empire/pricing'
      preLoaderRoute: typeof EmpirePricingRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/onboarding': {
      id: '/empire/onboarding'
      path: '/onboarding'
      fullPath: '/empire/onboarding'
      preLoaderRoute: typeof EmpireOnboardingRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/markets': {
      id: '/empire/markets'
      path: '/markets'
      fullPath: '/empire/markets'
      preLoaderRoute: typeof EmpireMarketsRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/legal': {
      id: '/empire/legal'
      path: '/legal'
      fullPath: '/empire/legal'
      preLoaderRoute: typeof EmpireLegalRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/koach': {
      id: '/empire/koach'
      path: '/koach'
      fullPath: '/empire/koach'
      preLoaderRoute: typeof EmpireKoachRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/grants': {
      id: '/empire/grants'
      path: '/grants'
      fullPath: '/empire/grants'
      preLoaderRoute: typeof EmpireGrantsRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/entity': {
      id: '/empire/entity'
      path: '/entity'
      fullPath: '/empire/entity'
      preLoaderRoute: typeof EmpireEntityRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/credit': {
      id: '/empire/credit'
      path: '/credit'
      fullPath: '/empire/credit'
      preLoaderRoute: typeof EmpireCreditRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/connections': {
      id: '/empire/connections'
      path: '/connections'
      fullPath: '/empire/connections'
      preLoaderRoute: typeof EmpireConnectionsRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/compliance': {
      id: '/empire/compliance'
      path: '/compliance'
      fullPath: '/empire/compliance'
      preLoaderRoute: typeof EmpireComplianceRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/community': {
      id: '/empire/community'
      path: '/community'
      fullPath: '/empire/community'
      preLoaderRoute: typeof EmpireCommunityRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/build': {
      id: '/empire/build'
      path: '/build'
      fullPath: '/empire/build'
      preLoaderRoute: typeof EmpireBuildRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/avatar': {
      id: '/empire/avatar'
      path: '/avatar'
      fullPath: '/empire/avatar'
      preLoaderRoute: typeof EmpireAvatarRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/ai-workers': {
      id: '/empire/ai-workers'
      path: '/ai-workers'
      fullPath: '/empire/ai-workers'
      preLoaderRoute: typeof EmpireAiWorkersRouteImport
      parentRoute: typeof EmpireRoute
    }
    '/empire/community/$businessId': {
      id: '/empire/community/$businessId'
      path: '/$businessId'
      fullPath: '/empire/community/$businessId'
      preLoaderRoute: typeof EmpireCommunityBusinessIdRouteImport
      parentRoute: typeof EmpireCommunityRoute
    }
  }
}

interface EmpireCommunityRouteChildren {
  EmpireCommunityBusinessIdRoute: typeof EmpireCommunityBusinessIdRoute
}

const EmpireCommunityRouteChildren: EmpireCommunityRouteChildren = {
  EmpireCommunityBusinessIdRoute: EmpireCommunityBusinessIdRoute,
}

const EmpireCommunityRouteWithChildren = EmpireCommunityRoute._addFileChildren(
  EmpireCommunityRouteChildren,
)

interface EmpireRouteChildren {
  EmpireAiWorkersRoute: typeof EmpireAiWorkersRoute
  EmpireAvatarRoute: typeof EmpireAvatarRoute
  EmpireBuildRoute: typeof EmpireBuildRoute
  EmpireCommunityRoute: typeof EmpireCommunityRouteWithChildren
  EmpireComplianceRoute: typeof EmpireComplianceRoute
  EmpireConnectionsRoute: typeof EmpireConnectionsRoute
  EmpireCreditRoute: typeof EmpireCreditRoute
  EmpireEntityRoute: typeof EmpireEntityRoute
  EmpireGrantsRoute: typeof EmpireGrantsRoute
  EmpireKoachRoute: typeof EmpireKoachRoute
  EmpireLegalRoute: typeof EmpireLegalRoute
  EmpireMarketsRoute: typeof EmpireMarketsRoute
  EmpireOnboardingRoute: typeof EmpireOnboardingRoute
  EmpirePricingRoute: typeof EmpirePricingRoute
  EmpireRevenueRoute: typeof EmpireRevenueRoute
}

const EmpireRouteChildren: EmpireRouteChildren = {
  EmpireAiWorkersRoute: EmpireAiWorkersRoute,
  EmpireAvatarRoute: EmpireAvatarRoute,
  EmpireBuildRoute: EmpireBuildRoute,
  EmpireCommunityRoute: EmpireCommunityRouteWithChildren,
  EmpireComplianceRoute: EmpireComplianceRoute,
  EmpireConnectionsRoute: EmpireConnectionsRoute,
  EmpireCreditRoute: EmpireCreditRoute,
  EmpireEntityRoute: EmpireEntityRoute,
  EmpireGrantsRoute: EmpireGrantsRoute,
  EmpireKoachRoute: EmpireKoachRoute,
  EmpireLegalRoute: EmpireLegalRoute,
  EmpireMarketsRoute: EmpireMarketsRoute,
  EmpireOnboardingRoute: EmpireOnboardingRoute,
  EmpirePricingRoute: EmpirePricingRoute,
  EmpireRevenueRoute: EmpireRevenueRoute,
}

const EmpireRouteWithChildren =
  EmpireRoute._addFileChildren(EmpireRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpireRoute: EmpireRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
